### ISSUE TITLE
Loading not shown properly

### ISSUE THREAD

**Issue by Saachi30** [farisfaikar/wayry#13]
Please assign this issue to me, can add attractive loaders that show up whenever page is not fully loaded.

*Example loader*
![image](https://github.com/user-attachments/assets/db6b6820-8ac4-475a-a630-3521d3f73fd7)

**Comment by Saachi30** [comment]
Hey! Can you please share the postgres url which is there in your env? I
wont misuse it, but without that the app is crashing, need it only for
development purposes.

**Comment by farisfaikar** [comment]
Hi again! I'm emailing you the development posgres url at peswanisaachi@gmail.com. I hope it works!

**Comment by Saachi30** [comment]
Yes it worked! 


https://github.com/user-attachments/assets/4d5c38bd-2d33-46b0-a76d-993251e497a9

Here is the new loader which will function on every screen. If it looks good, should I make a pull request? Or if any changes are required then let me know!

**Comment by farisfaikar** [comment]
@Saachi30 Yes, it looks perfect! You should go ahead and make a PR for this now 😁
