### ISSUE TITLE
Convert Issue Templates from Markdown to YAML and Add Workflows

### ISSUE THREAD

**Issue by Brijeshthummar02** [farisfaikar/wayry#25]
**Is your feature request related to a problem? Please describe.**
I would like to enhance our repository by converting existing issue templates from Markdown (.md) to YAML (.yml) format and adding workflows for improved automation.

**Describe the solution you'd like**
1. Convert existing Markdown issue templates (bug_report.md, feature_request.md, feature_security_vulnerability.md) to YAML format (bug_report.yml, feature_request.yml, feature_security_vulnerability.yml).
2. Create or update the config.yml file in the .github/ISSUE_TEMPLATE directory to include the new YAML templates.
3. Add necessary workflows in the .github/workflows directory to automate testing, linting, and deployment.
4. Test the new templates to ensure they function correctly when creating issues.

**Describe alternatives you've considered**

**Additional context**
I have already started working on this issue, so please assign it to me.

**Comment by farisfaikar** [comment]
Sounds good! Keep me updated on the issue if you have any questions 🤩

**Comment by Brijeshthummar02** [comment]
@farisfaikar can we reopen it as there's miner change needed in autocomment file - contributing.md file refrence was wrong need to fix it ASAP. 
Thanks

**Comment by farisfaikar** [comment]
Sure thing

**Comment by Brijeshthummar02** [comment]
@farisfaikar task done, now review it and close the issue.

**Comment by farisfaikar** [comment]
Merged, thanks!
