### ISSUE TITLE
[UI] Align Back Button with Start Button

### ISSUE THREAD

**Issue by chriscorrales** [farisfaikar/wayry#29]
### What would you like to share?

Hi!
I think we should align the back button with the start of the Start button.
Before
![image](https://github.com/user-attachments/assets/8f6504ae-9359-4eec-b364-1d9d9afa72cf)

After
![image](https://github.com/user-attachments/assets/3196b7a1-3629-4b09-8cb7-85c79a21a826)

### ✨ Browser

Mozilla Firefox

### Checklist 🚀

- [X] I checked and didn't find similar [issue](https://github.com/vatsalsinghkv/easy-fix/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/vatsalsinghkv/easy-fix/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no).

**Comment by farisfaikar** [comment]
Yes! Please do. Currently, it's a link button, that's why there a padding there
